### ISSUE TITLE
error while running edgesDemo.m

### ISSUE THREAD

**Issue by crasse2** [pdollar/edges#26]
Hi there !

first thanks pdollar for sharing your work, the results are astonishing !

however i'm new to matlab and I got some problems trying to make it work :

I did everything carefully in the installation method but then when I try to run edgesDemo.m I got this error :

```
Error using imPadMex
Requested 137438953888x1726576853504x7598263500303858035 (17179869184.0GB) array exceeds 
maximum array size preference. Creation of arrays greater than 
this limit may take a long time and cause MATLAB to become unresponsive.
See array size limit or preference panel for more information.
```

and several others but they come from the first one I think 

```
Error in imPad (line 39)
J = imPadMex( I, pad, type );

Error in edgesDetect (line 52)
  I = imPad(I,p,'symmetric');

Error in edgesDemo (line 25)
tic, E=edgesDetect(I,model); toc
```

As I said i'm quite new to matlab and didn't find yet where this imPadMex error does come from, any help would be greatly appreciated.

**Comment by crasse2** [comment]
re,

sorry, in fact I managed to get it working simply by downgrading to Matlab 2016 (I was using the 2017) and everything works like a charm ! (again I tried it on several images and the results are awesome for lines/edges extraction, thanks for sharing your work !)

**Comment by Passagers123a** [comment]
I have met the same question,and I use the MATLAB type is R2018a.Could you means I need to change the Matlab to 2016?

**Comment by Passagers123a** [comment]
I have changed. But I face the same qusetions as R2018 and you faced ever. Could you tell me how to solve the problem?

**Comment by zchrissirhcz** [comment]
@crasse2 @Passagers123a 

After some debugging, I figure it out that `mwSize` type is defined differently:

- `int` in C, when matlab<=2016b
- `size_t` in C, i.e. `long unsigned int`, when matlab>=2017a

Since I'm using ubuntu16.04 x64_64, on which the default gcc compiler is 64bit, and:
```
sizeof(int) = 4
sizeof(mwSize) = 8
```
thus, it would make wrong result if we still casting an array of `mwSize` to array of `int`. By carefully modify variable types, I made `edgesDemo.m` works correctly in matlab2017b as in matlab2016b with original code.

By the way, I've pushed my modified version to github:

[edges](https://github.com/zchrissirhcz/edges/commit/aed536f5791963992059f168573b79c4fc486fa6)

[toolbox](https://github.com/zchrissirhcz/toolbox/commit/3b538b23038a887326c8630244ac2033072ec0f1)

however, I do not guarantee other functions work correctly on matlab2017b or higher.

**Comment by OdedHorowits** [comment]
@zchrissirhcz 
Thank you very much for your work.

**Please note that the fixed 'toolbox' must be mexed before the fixed 'edges'**, otherwise you run into troubles with the demos (getting 'Undefined function or variable 'edgesDetectMex'.' error).

**In addition, please notice to 'add the path and its subfolders' of the toolbox and the edges-toolbox**, otherwise you will get another error.

But apparently I still get an error...
Some good seconds after running 'edgesDemo' I get the following:

Invalid MEX-file
'/home/oded2/Documents/MATLAB/Pdollar-edges-master/private/edgesDetectMex.mexa64': dlopen:
cannot load any more object with static TLS.

Error in edgesDetect (line 57)
  if(nargout<4), [E,inds] = edgesDetectMex(model,I,chnsReg,chnsSim);

Error in edgesDemo (line 25)
tic, E=edgesDetect(I,model); toc

How can we fix that?
Thank you

**Edit: I have found the solution for that.**
The problem is related to Matlab loading too much libraries relating to hardware.
Matlab had reported that this issue was fixed in the 2016 version, but we all know that's is not true... :-)
So, since it's a hardware and its related libraries problem, I figured that maybe the new Ubuntu version would be better. Apparently, upgrading from Ubuntu 14.04 to 16.04 indeed solve the problem!

Oded

**Comment by huimxu** [comment]
@zchrissirhcz  faced the same problem when i modified the files in matlab 2018b, could you have any other solutions?

**Comment by OdedHorowits** [comment]
Hello,
I had replied a solution at the GitHub thread.
Hope you find it helpful.
Oded
כל טוב,
עודד הורוביץ

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09.01.19,
13:01:22

‫בתאריך יום ד׳, 9 בינו׳ 2019 ב-11:22 מאת ‪huimxu‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by zchrissirhcz** [comment]
@OdedHorowits Congratulate that you've solved your problem.
